import type { NextPage } from 'next'
import Head from 'next/head'
import About from '../components/About/About'
import Experience from '../components/Experience/Experience'
import Header from '../components/Header'
import Hero from '../components/Hero/Hero'
import Projects from '../components/Projects/Projects'
import Skills from '../components/Skills/Skills'

const Home: NextPage = () => {
  return (
    <div className="bg-[rgb(36,36,36)] scrollbar text-white h-screen relative snap-y snap-mandatory overflow-y-scroll overflow-x-hidden z-0">
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Header */}
      <Header />

      {/* Hero */}
      <section id='hero' className='snap-start'>
        <Hero />
      </section>

      {/* About */}
      <section id='about' className='snap-center'>
        <About />
      </section>

      {/* Experience */}
      <section id='about' className='snap-start'>
        <Experience />
      </section>

      {/* Skills */}
      <section id='skills' className='snap-start'>
        <Skills />
      </section>

      {/* Projects */}
      <section id='projects' className='snap-end'>
        <Projects />
      </section>

      {/* Contact Me */}


    </div>
  )
}

export default Home
